# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    build_check.yml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shtanemu <shtanemu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/02 14:39:41 by shtanemu          #+#    #+#              #
#    Updated: 2023/09/02 14:39:42 by shtanemu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Build check

on:
  pull_request:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install-build-essential
        run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: make
