# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    integration_test.yml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shtanemu <shtanemu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/02 17:23:39 by shtanemu          #+#    #+#              #
#    Updated: 2023/11/03 13:18:48 by shtanemu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Integration test

on:
  pull_request:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install-build-essential
        run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: make debug

      - name: Install libraries
        run: python -m pip install --upgrade pip setuptools && pip install -r requirement.txt

      - name: Set env variables
        run: |
          cd ./integrationtest
          echo HOST_NAME='127.0.0.1' >> .env
          echo PORT=8081 >> .env
          echo PROJECT_ROOT='../' >> .env
          echo CONFFILE='${PROJECT_ROOT}conf_files/test.conf' >> .env
          echo WEBSERV='${PROJECT_ROOT}webserv' >> .env

      - name: Run test
        run: |
          cd ./integrationtest
          bash run.sh remake

