# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    integration_test.yml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shtanemu <shtanemu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/02 17:23:39 by shtanemu          #+#    #+#              #
#    Updated: 2023/10/04 18:08:18 by shtanemu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Integration test

on:
  pull_request:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install-build-essential
        run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: make

      - name: Install libraries
        run: python -m pip install --upgrade pip setuptools && pip install -r requirement.txt

      - name: Run test
        run: |
          cd /code/integrationtest
          python runner.py tests
